### ISSUE TITLE
AsyncEventHandler<in TEventArgs> should be constraint to EventArgs

### ISSUE THREAD

**Issue by tsahi** [TAGC/AsyncEvent#2]
The event convention is that event handlers should accept an `EventArgs` or it's derivative as the second argument. But your `AsyncEventHandler<in TEventArgs>` can accept any type:
https://github.com/TAGC/AsyncEvent/blob/67636d1c0b4604f95c8374543bd230f40da6ae99/src/AsyncEvent/AsyncEventHandler.cs#L22

It should be augmented with a constraint, to `TEventArgs` which inherit from `EventArgs`:
```csharp
public delegate Task AsyncEventHandler<in TEventArgs>(object sender, TEventArgs eventArgs) where TEventArgs : EventArgs;
```

**Comment by TAGC** [comment]
I actually had it [like that originally](https://github.com/TAGC/AsyncEvent/commit/2f0ae9bae0cba373925b812c81074df00038ef02#diff-aa68e13ee39bd07d3b64236ab60ab9be), but removed the constraint on account of Microsoft's recommendations [here](https://docs.microsoft.com/en-us/dotnet/csharp/modern-events).
