### ISSUE TITLE
When a new version is going to be release?

### ISSUE THREAD

**Issue by ultimaweapon** [TAGC/AsyncEvent#6]
I have a plan to migrate my homegrown library to AsyncEvent but there is a bug that is not fixed yet in the master branch (#5). Do you have any plans to release a new version soon?

**Comment by TAGC** [comment]
Yeah I can start on a release now.

**Comment by ultimaweapon** [comment]
Awesome! Thanks!

**Comment by TAGC** [comment]
Released v0.2.1. The NuGet package is being indexed currently but should be available for download pretty soon. 👍
