### ISSUE TITLE
Task null

### ISSUE THREAD

**Issue by dazinator** [TAGC/AsyncEvent#7]
Should the sample in the readme be updated to return Task.CompletedTask rather the a NULL task when the event is not being handled - like so:

``` csharp
   private Task OnTemperatureChanged(double newTemperature) =>
        TemperatureChanged?.InvokeAsync(this, new TemperatureChangedEventArgs { Temperature = newTemperature }) ?? Task.CompletedTask;

```

Otherwise if you `await` it, and there happen to be no handlers, you'll get a null ref exception.

**Comment by TAGC** [comment]
Good catch, but actually `InvokeAsync` will return `Task.CompletedTask` if `TemperatureChanged` is null anyway:

https://github.com/TAGC/AsyncEvent/blob/fde90b090a0c86adbfdd200e53298413ea48bf9e/src/AsyncEvent/AsyncEventHandler.cs#L72-L83

This means I should just remove the safe dereference operator from that.

**Comment by TAGC** [comment]
I've made that change to the README on the develop branch. It'll get merged into master the next time I do a release.
